Issue 7
cul-it/order-import-poc pull request #12
Opened 2021-03-12 13:37 UTC by fereira

remove objectCode

2021-03-15 16:47 UTC, cappadona requested changes
Thanks @fereira.

First a few comments that apply to Pull Requests in general:
* I updated the PR title so it accurately summarizes the changes introduced and references the associated issue (aka **The WHAT**)
* I updated the PR description to describe the underlying reasoning behind the change (aka **The WHY**)
* I linked the PR to the associated issue using one of [GitHub's supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

> This format follows established Git commit message etiquette ([1], [2]) and is especially important here since we're using [GitHub's **Squash and merge** feature](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) which will automatically use the title of the PR as the commit message when merging.

Applying these conventions to this PR, will you please split out the testing changes into a separate PR?

* deleting `/marc-test-files/physical.mrc`
* a majority of the changes to `src/test/java/org/olf/folio/order/MarcReaderTest.java `

To be clear, I'm not saying that the issue to PR ratio must be 1:1. There is no problem with a PR addressing multiple related issues or even PRs that stand on their own without a linked issue.

As an example, I think it would be perfectly acceptable to retain the MARC field mapping changes as part of this PR, as long as:
1. The PR title and description are updated accordingly
1. The specs/requirements are finalized – at the moment #9 is still assigned to @starsplatter 

[1]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[2]: https://chris.beams.io/posts/git-commit/

2021-03-15 17:42 UTC, fereira commented
I was unaware that there were strict requirements/conventions for submitting a PR, especially one that only involved deleting a few lines.  It's going to take much longer to make changes to the PR than to actually fix the issue.  Frankly, I don't even know how to pull changes from one PR into a separate PR.   If it's going to take a few days just to commit changes to delete a handful of lines, whatever estimates there were for the issue #5,  can probably tripled.

2021-03-15 17:57 UTC, cappadona commented
No worries, @fereira. This cleanup is relatively simple using git's [`cherry-pick`](https://git-scm.com/docs/git-cherry-pick) and [`revert`](https://git-scm.com/docs/git-revert) commands. I've gone ahead and cherry-picked the 3 testing related commits from this PR into a new [`testing-enhancements` branch](https://github.com/cul-it/order-import-poc/compare/main...cul-it:testing-enhancements).

I can revert these from this PR if you would like, just let me know.

As for the MARC field mapping, @starsplatter do you still have more work remaining to [finalize the specs](https://github.com/cul-it/order-import-poc/issues/9) or are they complete and ready to be implemented?

2021-03-16 15:52 UTC, cappadona commented
Okay @fereira.  I've reverted the unrelated testing and MARC field mapping changes. You want to take this for a spin and ensure it's working properly?

2021-03-16 16:15 UTC, fereira commented
I'm not even sure what I'm testing at this point but I see if it's working

2021-03-16 16:26 UTC, cappadona approved these changes
Good to go. Thanks @fereira

2021-03-16 16:28 UTC, merged