remove return responseMessages inside loop which reads records.
cul-it/order-import-poc pull request #25
Opened 2021-04-29 13:26 UTC by fereira

resolves #24

2021-05-04 21:31 UTC, cappadona commented
@fereira Is this ready for review?

2021-05-05 14:06 UTC, cappadona requested changes

2021-05-05 14:06 UTC, cappadona commented on src/main/java/org/olf/folio/order/OrderImport.java
> +                        return responseMessages();
Two questions:

1. Should this be:
   ```suggestion
		    	return responseMessages;
   ```
1. Don't we also want to drop the other early return on line 531?
https://github.com/cul-it/order-import-poc/blob/3e5dd3a5bda4fc22ed2772f1f3668b9a354d1949/src/main/java/org/olf/folio/order/OrderImport.java#L531

2021-05-05 14:20 UTC, fereira commented
Yes, to the first question...it should not be trying to return a method.  I've pushed an update that can be re-reviewed

No to the second.  That line is actually returning a responseMessage when an error has occurred.  I've though about changing the responseMessage name to errorMessage to avoid the confusion....it would occur in quite a few places.

2021-05-05 14:24 UTC, cappadona commented on src/main/java/org/olf/folio/order/OrderImport.java
> +                        return responseMessages();
Thanks @fereira. Are you sure about line 531?

It looks to me like it's returning the outer `responseMessages` JSONArray and not the inner `responseMessage` JSONObject, but would be good for you to double check because I have gotten tripped up by these names multiple times as I reviewed this.

2021-05-05 14:57 UTC, fereira commented
Now I'm confused.  The OrderImport.java class that I have for this branch line at 531 is much different.  That check is at line 614 in my version.  I can change all of the JSONObjects and JSONArray that is for returning an error to errorMessage and errorMessages but it seems to me that a strict adherence to process is significantly increasing how much time I'm spending on this and has reduced my confidence in what I'm actually changing.

2021-05-06 13:04 UTC, closed without merging

2021-05-06 13:40 UTC, cappadona commented
Thanks for closing this @fereira and opening #33 as a replacement. Are you good with me deleting the `fix-mrc-validation` branch?

2021-05-06 13:44 UTC, fereira commented
Yes, go ahead