add identfifiers and contributors to poLine and vendorCode and ISBN to response
cul-it/order-import-poc pull request #58
Opened 2021-06-09 14:36 UTC by fereira

This PR uses to buildIdentifiers and buildContributors methods to obtain identifiers and contributors to be added to the po line.  It has to rename element names (e.g. change "name" to "contributor") in order to produce valid JSON for the order line.  It also adds the vendorCode and the first ISBN number from the identifiers list to the response.

This partially resolves #48 and #49.  The front end jsp still needs to be updated to display the vendorCode and ISBN,

This PR also resolves #52 and #57

In order to facilitate testing of this functionality, the buildIdentifiers and buildContributors methods have been moved to the MarcUtils class and junit tests have been added.

2021-06-09 22:15 UTC, cappadona requested changes
This looks pretty good. Some inline comments/suggestions.

The one piece I noticed that's not functioning properly is that the generated PO lines only have the first ISBN, even though the JSON body you `POST` when generating the composite order includes a valid array with multiple items for`details.productIds`.
> The Inventory Instance successfully stores all ISBNs as resource identifiers

I did a [quick search in FOLIO Jira](https://issues.folio.org/browse/MODORDERS-262?jql=text%20~%20productIds) for an existing ticket but came up empty. I suspect this is not a deal breaker and we should proceed as is with the first ISBN only on the POL, but I'm deferring to and pinging @natalyapik & @starsplatter.

2021-06-09 22:15 UTC, cappadona commented on src/main/java/org/olf/folio/order/OrderImport.java
> +                }
Why not just get the ISBNs for the `responseMessage` from `polDetails` JSONObject along with `receivingNote`?
> see line 412 above

2021-06-09 22:31 UTC, fereira commented on src/main/java/org/olf/folio/order/OrderImport.java
> +                // TODO: Fix but that causes 422 response if productIds are addet to details in poLine
I was getting a 422 error when executing the PUT request to inventory/instances/{instanceID} *if* identifiers had been added to the poLine....after some refactoring, it went away.

2021-06-09 22:33 UTC, starsplatter commented
Hi @cappadona at least one of the ISBN cases seems to be that the order app converts the short isbn to the long isbn, and then is nice enough to de-dupe? I think.

2021-06-09 22:36 UTC, cappadona commented on src/main/java/org/olf/folio/order/OrderImport.java
> +                // TODO: Fix but that causes 422 response if productIds are addet to details in poLine
Gotcha. If it was prior to your full refactoring of `buildIdentifiers` but after you [split out the `qualifier`](https://github.com/cul-it/order-import-poc/issues/52#issuecomment-853961229) and you were sending the same array to both endpoints, that _could_ explain why you were getting a `422` for the inventory endpoint since it doesn't support the `qualifier` key.

Glad you got it sorted.

2021-06-09 22:37 UTC, fereira commented on src/main/java/org/olf/folio/order/OrderImport.java
> +                }
I'll have to take a look at that.  I may be able to pull the identifiers and contributors from the polDetails but the array element names are different in the poLine (productIds instead of identifiers) than what is expected in the instance JSON.    If there is an ISBN conversion happening, it's not happening in the in  the app, but in folio after the ISBN numbers have been posted.

2021-06-09 22:38 UTC, cappadona commented on src/main/java/org/olf/folio/order/OrderImport.java
> +                // TODO: Fix but that causes 422 response if productIds are addet to details in poLine
```suggestion
```

2021-06-09 22:43 UTC, cappadona commented on src/main/java/org/olf/folio/order/OrderImport.java
> +                }
Yeah, the (maybe) downside of getting the ISBNs from the `polDeetails` is that it looks like the orders app is only storing one, unless every example I've hit can be attributed to the orders app deduping ISBNs as [Jenn suggested below](https://github.com/cul-it/order-import-poc/pull/58#issuecomment-858145244) :)

> ** At the moment it wouldn't be a change to the current behavior since only the first ISBN is placed in the `responseMessage`

2021-06-10 12:03 UTC, cappadona commented
Thanks @starsplatter. I tried a couple more files this morning and the orders app does indeed dedupe the ISBNs. Thanks for catching that!

2021-06-10 12:19 UTC, fereira commented
I can also confirm that when a po is posted with a poLine which contains a productIds array in a polDetais element with multiple, unique ISBNs, that only one productId is returned when getting the updatedPurchaseOrder.

2021-06-10 12:28 UTC, cappadona commented
@fereira Try submitting `requesters_5-records_2021-03-11.mrc` and you'll see that multiple ISBNs are stored by `mod-orders` and returned when retrieving the composite order.

Here's an example I already submitted:
https://cornell-training.folio.ebsco.com/orders/lines/view/d5cdb81e-d600-408f-a274-e233e9011e7a

2021-06-10 12:59 UTC, fereira commented
Okay, I can see that  it will store multiiple productIds but it's still returning fewer elements in the array that were submitted.  I can't see any sort of pattern for what some aren't persisted

2021-06-10 13:04 UTC, cappadona commented
@fereira the orders app is deduping ISBNs within a single PO Line, as identified by @starsplatter

> Hi @cappadona at least one of the ISBN cases seems to be that the order app converts the short isbn to the long isbn, and then is nice enough to de-dupe? I think.

2021-06-10 13:42 UTC, fereira commented
Since I think I've addressed everything else in the PR,   can we deal with how to handle identifiers with another issue (if necessary).

2021-06-10 13:44 UTC, cappadona commented
That works for me, just waiting on feedback from @natalyapik. In the meantime, are you good with me adding a commit to render the vendor code and ISBN to the results?

2021-06-10 14:02 UTC, cappadona commented
@fereira I got the thumbs up from @natalyapik via Slack. I also:
* pushed [a commit](https://github.com/cul-it/order-import-poc/pull/58/commits/90304bcd8764fa655392a8e7455454e8f0e961bb) to add vendor code and ISBN to the results
* update the environment variables so the next deployment will point the app to `cornell-test`

Feel free to merge when ready.

2021-06-10 14:02 UTC, cappadona approved these changes

2021-06-10 14:23 UTC, merged